(in-package #:dsh-lisp-runtime)

;; This bridge deliberately keeps the runtime dependency-free. It is a small
;; JSONL transport for the TypeScript adapter, not a second Host implementation.

(defparameter +dsh-json-false+ :json-false)

(defstruct (dsh-json-object (:constructor make-dsh-json-object (pairs))) pairs)
(defstruct (dsh-json-array (:constructor make-dsh-json-array (values))) values)

(defun dsh-json-plist-p (value)
  (and (listp value)
       (evenp (length value))
       (loop for (key ignored) on value by #'cddr
             always (keywordp key))))

(defun dsh-json-key (key)
  (string-downcase (string key)))

(defun dsh-json->wire (value)
  (cond
    ((typep value 'dsh-json-object) value)
    ((typep value 'dsh-json-array) value)
    ((null value) nil)
    ((eq value +dsh-json-false+) +dsh-json-false+)
    ((eq value t) t)
    ((or (stringp value) (numberp value)) value)
    ((dsh-json-plist-p value)
     (make-dsh-json-object
      (loop for (key item) on value by #'cddr
            collect (cons (dsh-json-key key) (dsh-json->wire item)))))
    ((listp value)
     (make-dsh-json-array (mapcar #'dsh-json->wire value)))
    ((vectorp value)
     (make-dsh-json-array (map 'list #'dsh-json->wire value)))
    ((symbolp value) (string-downcase (symbol-name value)))
    (t (princ-to-string value))))

(defun dsh-wire->lisp (value)
  (cond
    ((typep value 'dsh-json-object)
     (loop for (key . item) in (dsh-json-object-pairs value)
           append (list (intern (string-upcase key) :keyword)
                        (dsh-wire->lisp item))))
    ((typep value 'dsh-json-array)
     (mapcar #'dsh-wire->lisp (dsh-json-array-values value)))
    ((eq value +dsh-json-false+) +dsh-json-false+)
    (t value)))

(defun dsh-json-write-string (value stream)
  (write-char #\" stream)
  (loop for character across value do
    (case character
      (#\" (write-string "\\\"" stream))
      (#\\ (write-string "\\\\" stream))
      (#\Newline (write-string "\\n" stream))
      (#\Return (write-string "\\r" stream))
      (#\Tab (write-string "\\t" stream))
      (otherwise
       (if (< (char-code character) 32)
           (format stream "\\u~4,'0X" (char-code character))
           (write-char character stream)))))
  (write-char #\" stream))

(defun dsh-json-write (value stream)
  (cond
    ((typep value 'dsh-json-object)
     (write-char #\{ stream)
     (loop for (pair . rest) on (dsh-json-object-pairs value)
           do (dsh-json-write-string (car pair) stream)
              (write-char #\: stream)
              (dsh-json-write (cdr pair) stream)
              (when rest (write-char #\, stream)))
     (write-char #\} stream))
    ((typep value 'dsh-json-array)
     (write-char #\[ stream)
     (loop for item in (dsh-json-array-values value)
           for first = t then nil
           do (unless first (write-char #\, stream))
              (dsh-json-write item stream))
     (write-char #\] stream))
    ((eq value +dsh-json-false+) (write-string "false" stream))
    ((null value) (write-string "null" stream))
    ((eq value t) (write-string "true" stream))
    ((stringp value) (dsh-json-write-string value stream))
    ((numberp value) (princ value stream))
    (t (dsh-json-write-string (princ-to-string value) stream))))

(defun dsh-json-encode (value)
  (with-output-to-string (stream)
    (dsh-json-write (dsh-json->wire value) stream)))

(defstruct (dsh-json-parser (:constructor make-dsh-json-parser (text)))
  text
  (index 0))

(defun dsh-json-peek (parser)
  (let ((index (dsh-json-parser-index parser))
        (text (dsh-json-parser-text parser)))
    (and (< index (length text)) (char text index))))

(defun dsh-json-take (parser)
  (let ((value (dsh-json-peek parser)))
    (when value (incf (dsh-json-parser-index parser)))
    value))

(defun dsh-json-error (parser message)
  (error "JSON parse error at offset ~D: ~A"
         (dsh-json-parser-index parser) message))

(defun dsh-json-skip-space (parser)
  (loop while (and (dsh-json-peek parser)
                   (find (dsh-json-peek parser)
                         '(#\Space #\Tab #\Return #\Newline)
                         :test #'char=))
        do (dsh-json-take parser)))

(defun dsh-json-expect (parser expected)
  (unless (char= (or (dsh-json-take parser) #\Null) expected)
    (dsh-json-error parser (format nil "expected ~C" expected))))

(defun dsh-json-string (parser)
  (dsh-json-expect parser #\")
  (with-output-to-string (stream)
    (loop
      (let ((character (dsh-json-take parser)))
        (when (null character) (dsh-json-error parser "unterminated string"))
        (cond
          ((char= character #\") (return))
          ((char= character #\\)
           (let ((escape (dsh-json-take parser)))
             (when (null escape) (dsh-json-error parser "unterminated escape"))
             (case escape
               (#\" (write-char #\" stream))
               (#\\ (write-char #\\ stream))
               (#\/ (write-char #\/ stream))
               (#\b (write-char #\Backspace stream))
               (#\f (write-char #\Page stream))
               (#\n (write-char #\Newline stream))
               (#\r (write-char #\Return stream))
               (#\t (write-char #\Tab stream))
               (#\u
                (let ((hex (make-string 4)))
                  (dotimes (index 4)
                    (setf (char hex index) (or (dsh-json-take parser) #\Null)))
                  (let ((code (ignore-errors (parse-integer hex :radix 16))))
                    (unless code (dsh-json-error parser "invalid unicode escape"))
                    (let ((unicode (code-char code)))
                      (unless unicode (dsh-json-error parser "invalid unicode codepoint"))
                      (write-char unicode stream)))))
               (otherwise (dsh-json-error parser "invalid string escape")))))
          ((< (char-code character) 32)
           (dsh-json-error parser "unescaped control character"))
          (t (write-char character stream)))))))

(defun dsh-json-number (parser)
  (let ((start (dsh-json-parser-index parser)))
    (when (char= (or (dsh-json-peek parser) #\Null) #\-)
      (dsh-json-take parser))
    (let ((first (dsh-json-peek parser)))
      (cond
        ((char= (or first #\Null) #\0)
         (dsh-json-take parser)
         (when (digit-char-p (dsh-json-peek parser))
           (dsh-json-error parser "leading zero in number")))
        ((and first (digit-char-p first))
         (loop while (and (dsh-json-peek parser)
                          (digit-char-p (dsh-json-peek parser)))
               do (dsh-json-take parser)))
        (t (dsh-json-error parser "number must start with a digit"))))
    (when (char= (or (dsh-json-peek parser) #\Null) #\.)
      (dsh-json-take parser)
      (unless (digit-char-p (dsh-json-peek parser))
        (dsh-json-error parser "fraction must contain a digit"))
      (loop while (and (dsh-json-peek parser)
                       (digit-char-p (dsh-json-peek parser)))
            do (dsh-json-take parser)))
    (when (and (dsh-json-peek parser)
               (find (dsh-json-peek parser) "eE" :test #'char=))
      (dsh-json-take parser)
      (when (and (dsh-json-peek parser)
                 (find (dsh-json-peek parser) "+-" :test #'char=))
        (dsh-json-take parser))
      (unless (digit-char-p (dsh-json-peek parser))
        (dsh-json-error parser "exponent must contain a digit"))
      (loop while (and (dsh-json-peek parser)
                       (digit-char-p (dsh-json-peek parser)))
            do (dsh-json-take parser)))
    (let ((text (subseq (dsh-json-parser-text parser)
                        start (dsh-json-parser-index parser))))
      (handler-case
          (multiple-value-bind (value position) (read-from-string text)
            (if (and (numberp value) (= position (length text)))
                value
                (dsh-json-error parser "invalid number")))
        (error () (dsh-json-error parser "invalid number"))))))

(defun dsh-json-literal (parser literal value)
  (loop for expected across literal
        unless (char= (or (dsh-json-take parser) #\Null) expected)
          do (dsh-json-error parser (format nil "expected ~A" literal)))
  value)

(declaim (ftype function dsh-json-value dsh-json-object-value dsh-json-array-value))

(defun dsh-json-value (parser)
  (dsh-json-skip-space parser)
  (case (dsh-json-peek parser)
    (#\{ (dsh-json-object-value parser))
    (#\[ (dsh-json-array-value parser))
    (#\" (dsh-json-string parser))
    (#\t (dsh-json-literal parser "true" t))
    (#\f (dsh-json-literal parser "false" +dsh-json-false+))
    (#\n (dsh-json-literal parser "null" nil))
    (otherwise
     (if (or (char= (or (dsh-json-peek parser) #\Null) #\-)
             (digit-char-p (or (dsh-json-peek parser) #\Null)))
         (dsh-json-number parser)
         (dsh-json-error parser "unexpected JSON token")))))

(defun dsh-json-object-value (parser)
  (dsh-json-expect parser #\{)
  (dsh-json-skip-space parser)
  (let ((pairs nil))
    (unless (char= (or (dsh-json-peek parser) #\Null) #\})
      (loop
        (dsh-json-skip-space parser)
        (unless (char= (or (dsh-json-peek parser) #\Null) #\")
          (dsh-json-error parser "object keys must be strings"))
        (let ((key (dsh-json-string parser)))
          (dsh-json-skip-space parser)
          (dsh-json-expect parser #\:)
          (push (cons key (dsh-json-value parser)) pairs))
        (dsh-json-skip-space parser)
        (if (char= (or (dsh-json-peek parser) #\Null) #\})
            (return)
            (dsh-json-expect parser #\,))))
    (dsh-json-expect parser #\})
    (make-dsh-json-object (nreverse pairs))))

(defun dsh-json-array-value (parser)
  (dsh-json-expect parser #\[)
  (dsh-json-skip-space parser)
  (let ((values nil))
    (unless (char= (or (dsh-json-peek parser) #\Null) #\])
      (loop
        (push (dsh-json-value parser) values)
        (dsh-json-skip-space parser)
        (if (char= (or (dsh-json-peek parser) #\Null) #\])
            (return)
            (dsh-json-expect parser #\,))))
    (dsh-json-expect parser #\])
    (make-dsh-json-array (nreverse values))))

(defun dsh-json-decode (text)
  (let ((parser (make-dsh-json-parser text)))
    (let ((value (dsh-json-value parser)))
      (dsh-json-skip-space parser)
      (when (dsh-json-peek parser) (dsh-json-error parser "trailing data"))
      value)))

(defstruct (dsh-jsonrpc-server (:constructor %make-dsh-jsonrpc-server))
  runtime
  (agents (make-hash-table :test #'equal)))

(defun make-jsonrpc-server (&key (runtime (make-runtime)))
  (%make-dsh-jsonrpc-server :runtime runtime))

(defun dsh-jsonrpc-agent (server session-id)
  (require-string session-id "session-id")
  (or (gethash session-id (dsh-jsonrpc-server-agents server))
      (let ((agent (make-agent :runtime (dsh-jsonrpc-server-runtime server)
                               :session-id session-id)))
        (install-self-tools agent)
        (setf (gethash session-id (dsh-jsonrpc-server-agents server)) agent)
        agent)))

(defun dsh-jsonrpc-form (text)
  (require-string text "form")
  (let ((*read-eval* nil))
    (multiple-value-bind (form position) (read-from-string text nil nil)
      (unless form (fail 'dsh-validation-error "form must contain one Lisp form"))
      (when (find-if-not (lambda (character)
                           (find character '(#\Space #\Tab #\Return #\Newline)
                                 :test #'char=))
                         text :start position)
        (fail 'dsh-validation-error "form must contain exactly one Lisp form"))
      form)))

(defun dsh-jsonrpc-form-text (form)
  (with-output-to-string (stream)
    (let ((*print-readably* t)) (write form :stream stream))))

(defun dsh-jsonrpc-inspect-package (runtime session-id plugin-id package-id)
  (let ((result (inspect-package runtime session-id plugin-id package-id)))
    (list :mode :package
          :plugin-id (getf result :plugin-id)
          :package-id (getf result :package-id)
          :name (getf result :name)
          :purpose (getf result :purpose)
          :current-package-id (getf result :current-package-id)
          :next-package-id (getf result :next-package-id)
          :form (dsh-jsonrpc-form-text (getf result :code))
          :runtime (getf result :runtime))))

(defun dsh-jsonrpc-method (server agent method params)
  (let ((runtime (dsh-jsonrpc-server-runtime server))
        (session-id (agent-session-id agent)))
    (cond
      ((string= method "cordis/inspect")
       (cond
         ((getf params :package-id)
          (dsh-jsonrpc-inspect-package runtime session-id
                                       (getf params :plugin-id)
                                       (getf params :package-id)))
         ((getf params :plugin-id)
          (inspect-plugin runtime session-id (getf params :plugin-id)))
         (t (agent-inspect agent))))
      ((string= method "cordis/define")
       (define-package runtime session-id
                       :plugin-id (getf params :plugin-id)
                       :id-prefix (or (getf params :id-prefix) "dsh")
                       :name (getf params :name)
                       :purpose (getf params :purpose)
                       :form (dsh-jsonrpc-form (getf params :form))))
      ((string= method "cordis/run")
       (activate-package runtime session-id
                         (getf params :plugin-id)
                         (getf params :package-id)
                         :mode (intern (string-upcase (or (getf params :mode) "run"))
                                       :keyword)))
      ((string= method "cordis/rollback")
       (rollback-plugin runtime session-id (getf params :plugin-id)))
      ((string= method "cordis/stop")
       (stop-plugin runtime session-id (getf params :plugin-id)))
      ((string= method "cordis/undefine")
       (undefine-plugin runtime session-id (getf params :plugin-id)))
      ((string= method "cordis/invoke")
       (runtime-invoke runtime session-id
                       (getf params :plugin-id)
                       (getf params :plugin-run-id)
                       (getf params :method)
                       (getf params :arguments)))
      ((string= method "cordis/tool")
       (agent-call-tool agent (getf params :name) (getf params :arguments)))
      (t (error "method not found: ~A" method)))))

(defun dsh-jsonrpc-result (id value)
  (list :jsonrpc "2.0" :id id :result value))

(defun dsh-jsonrpc-error (id code message)
  (list :jsonrpc "2.0" :id id
        :error (list :code code :message message)))

(defun dsh-jsonrpc-dispatch (server request)
  (let ((id nil))
    (handler-case
        (let* ((value (if (stringp request) (dsh-wire->lisp (dsh-json-decode request)) request))
               (method (and (dsh-json-plist-p value) (getf value :method)))
               (params (and (dsh-json-plist-p value) (or (getf value :params) nil))))
          (setf id (and (dsh-json-plist-p value) (getf value :id)))
          (unless (and (dsh-json-plist-p value) (stringp method)
                       (or (null params) (dsh-json-plist-p params)))
            (return-from dsh-jsonrpc-dispatch
              (dsh-jsonrpc-error id -32600 "invalid JSON-RPC request")))
          (let ((agent (dsh-jsonrpc-agent server (or (getf params :session-id) "default"))))
            (dsh-jsonrpc-result id (dsh-jsonrpc-method server agent method params))))
      (dsh-error (condition)
        (dsh-jsonrpc-error id -32000 (dsh-error-message condition)))
      (error (condition)
        (dsh-jsonrpc-error id -32603 (princ-to-string condition))))))

(defun serve-jsonrpc (server &optional (input *standard-input*)
                                      (output *standard-output*))
  (loop for line = (read-line input nil nil)
        while line do
          (let ((response (dsh-jsonrpc-dispatch server line)))
            (write-line (dsh-json-encode response) output)
            (finish-output output)))
  server)
